default_context:
  _pegasus_version: 2024.1.2
  author_name: Shahbaz Khan
  ci: github_actions
  css_framework: bootstrap
  css_theme: bootstrap-material
  database: postgres
  deploy_platform: digital_ocean_app_platform
  description: B2B SaaS web application to allow customers to sell and design custom
    Tshirts.
  docker_setup: arm64
  domain_name: localhost:8000
  email: shahbaz@consulminds.com
  enable_github_login: n
  enable_google_login: n
  enable_twitter_login: n
  front_end_framework: react
  include_static_files: y
  marketing_email_platform: mailchimp
  post_process: y
  project_name: AIction ReAIction
  project_slug: aiction_reaiction
  stripe_payment_mode: checkout
  subscription_billing_model: per_unit
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: y
  use_api_keys: n
  use_async_example: n
  use_cloud_media_storage: y
  use_debug_toolbar: y
  use_docker: y
  use_ecommerce_example: y
  use_examples: y
  use_impersonation: y
  use_openai: y
  use_sentry: y
  use_subscriptions: y
  use_teams: y
  use_teams_example: y
  use_translations: y
  use_wagtail: n
